name: Automated API testing using Postman

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Wait for server to start.
        run: sleep 150
      - name: Run API tests
        run: |
          postman collection run "33475305-2409567f-8678-4cc3-9de2-885b736aa335"
